# Generated by Django 3.2 on 2021-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
